### ISSUE TITLE
Infonäytön wapputeksi

### ISSUE THREAD

**Issue by Veleema** [fyysikkokilta/fk-infonaytto-v2#1]
Sen pitäisi olla aikaa mahdolliseen wappuun >:(

**Comment by summis** [comment]
Hei Velema!

Kiitos tästä tarkasta huomiosta. Olet aivan oikeassa. Asia korjataan enstitilassa!

Ystävällisin terveisin,
Summila

**Comment by ApsiV11** [comment]
Korjattu! 👍
